name: PDF to Image Converter

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymupdf Pillow

      - name: Convert PDF to Image
        run: |
          python -c "
          import fitz
          doc = fitz.open('input.pdf')
          page = doc.load_page(0)
          pix = page.get_pixmap(matrix=fitz.Matrix(4, 4))
          pix.save('output.png')
          print('转换完成！')
          "

      - name: Upload output image
        uses: actions/upload-artifact@v4
        with:
          name: output-image
          path: output.png
